import About from '../pages/docs/base/about'
import Attachment from '../pages/docs/base/attachment'
import Checkbox from '../pages/docs/base/checkbox'
import Button from '../pages/docs/base/button'
import DropdownMenu from '../pages/docs/base/dropdownMenu'
import Icon from '../pages/docs/base/icon'
import Input from '../pages/docs/base/input'
import Menu from '../pages/docs/base/menu'
import Modal from '../pages/docs/base/modal'
import Notification from '../pages/docs/base/notification'
import RadioButtons from '../pages/docs/base/radioButtons'
import Scrollspy from '../pages/docs/base/scrollspy'
import Select from '../pages/docs/base/select'
import Sticky from '../pages/docs/base/sticky'
import Switch from '../pages/docs/base/switch'
import Tappable from '../pages/docs/base/tappable'
import Tooltip from '../pages/docs/base/tooltip'
import ZContext from '../pages/docs/base/zContext'

export default [
	{path: 'about', component: About},
	{path: 'attachment', component: Attachment},
	{path: 'button', component: Button},
	{path: 'checkbox', component: Checkbox},
	{path: 'dropdown-menu', component: DropdownMenu},
	{path: 'input', component: Input},
	{path: 'icon', component: Icon},
	{path: 'menu', component: Menu},
	{path: 'modal', component: Modal},
	{path: 'notification', component: Notification},
	{path: 'radio-buttons', component: RadioButtons},
	{path: 'scrollspy', component: Scrollspy},
	{path: 'select', component: Select},
	{path: 'sticky', component: Sticky},
	{path: 'switch', component: Switch},
	{path: 'tappable', component: Tappable},
	{path: 'tooltip', component: Tooltip},
	{path: 'zcontext', component: ZContext}
]
